package com.sola.dao.sys;

import com.sola.entity.sys.SysMenu;
import com.sola.utils.persistence.annotation.MyBatisDao;

@MyBatisDao
public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Mon Oct 29 17:43:16 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Mon Oct 29 17:43:16 CST 2018
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Mon Oct 29 17:43:16 CST 2018
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Mon Oct 29 17:43:16 CST 2018
     */
    SysMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Mon Oct 29 17:43:16 CST 2018
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Mon Oct 29 17:43:16 CST 2018
     */
    int updateByPrimaryKey(SysMenu record);
}