package com.sola.dao.sys;

import com.sola.entity.sys.SysRoleMenu;
import com.sola.utils.persistence.annotation.MyBatisDao;

@MyBatisDao
public interface SysRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Mon Oct 29 17:49:44 CST 2018
     */
    int insert(SysRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu
     *
     * @mbg.generated Mon Oct 29 17:49:44 CST 2018
     */
    int insertSelective(SysRoleMenu record);
}