package com.sola.dao.sys;

import com.sola.entity.sys.SysRole;
import com.sola.utils.persistence.annotation.MyBatisDao;

import java.util.List;

@MyBatisDao
public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Oct 29 17:36:18 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Oct 29 17:36:18 CST 2018
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Oct 29 17:36:18 CST 2018
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Oct 29 17:36:18 CST 2018
     */
    SysRole selectByPrimaryKey(String id);

    List<SysRole> findList(SysRole role) ;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Oct 29 17:36:18 CST 2018
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Mon Oct 29 17:36:18 CST 2018
     */
    int updateByPrimaryKey(SysRole record);
}