package com.sola.dao.sys;

import com.sola.entity.sys.SysUserRole;
import com.sola.utils.persistence.annotation.MyBatisDao;

@MyBatisDao
public interface SysUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Oct 29 17:54:15 CST 2018
     */
    int insert(SysUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role
     *
     * @mbg.generated Mon Oct 29 17:54:15 CST 2018
     */
    int insertSelective(SysUserRole record);
}