package com.sola.dao.demo;

import com.sola.entity.demo.Demo;
import com.sola.utils.persistence.annotation.MyBatisDao;

@MyBatisDao
public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    int insert(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    int insertSelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    Demo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    int updateByPrimaryKeySelective(Demo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Demo record);
}