package com.sola.entity.demo;

import com.sola.common.BaseEntity;

public class Demo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.buffer
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    private String buffer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.buffer
     *
     * @return the value of demo.buffer
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    public String getBuffer() {
        return buffer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.buffer
     *
     * @param buffer the value for demo.buffer
     *
     * @mbg.generated Wed Jun 06 15:42:14 CST 2018
     */
    public void setBuffer(String buffer) {
        this.buffer = buffer == null ? null : buffer.trim();
    }
}